[phases.setup]
nixPkgs = ["php82", "php82Extensions.intl", "php82Extensions.mbstring"]

[phases.build]
cmds = ["composer install --optimize-autoloader --no-interaction --ignore-platform-req=ext-intl"]

[start]
cmd = "php -S 0.0.0.0:$PORT -t public"